FROM apache/kafka:latest
USER root
RUN apk update && \
    apk add iproute2-tc

# Go back to default alpine user
USER appuser 

# Download the OpenTelemetry JAR for Kafka Brokers to use
RUN cd /tmp && \
    wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.0.0/opentelemetry-javaagent.jar