version: '3'
services:
  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: q_ArPuYrTNe3KmEBVQ8CAA
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "CONTROLLER://kafka1:9093,LISTENER://kafka1:9092"
      KAFKA_ADVERTISED_LISTENERS: LISTENER://kafka1:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,LISTENER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER
  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9092"
    environment:
      CLUSTER_ID: q_ArPuYrTNe3KmEBVQ8CAA
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: "CONTROLLER://kafka2:9093,LISTENER://kafka2:9092"
      KAFKA_ADVERTISED_LISTENERS: LISTENER://kafka2:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,LISTENER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER
  kafka3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9094:9092"
    environment:
      CLUSTER_ID: q_ArPuYrTNe3KmEBVQ8CAA
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: "CONTROLLER://kafka3:9093,LISTENER://kafka3:9092"
      KAFKA_ADVERTISED_LISTENERS: LISTENER://kafka3:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,LISTENER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER      